apiVersion: apps/v1
kind: Deployment
metadata:
  name: moj-projekat
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: moj-kontejner
        image: mikikg45/test-provera:feat-argocd-gitops-deploy-fda3e12
        command: ["python", "server.py"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: moj-servis
  namespace: default
spec:
  type: NodePort
  selector:
    app: test-app      # Here we select the pods with the label "app: test-app" to be part of this service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # Fixed nodePort to a specific value for easier access, you can change it if needed
