name: Terraform GitHub Teams

on:
  push:
    branches: ["main"]
    paths: ["terraform/**"]
  pull_request:
    branches: ["main"]
    paths: ["terraform/**"]

defaults:
  run:
    working-directory: terraform

env:
  GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_PAT }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKKEN }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -input=false -auto-approve
